# Generated by Django 6.0.6 on 2026-06-23 21:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ginrecipe',
            name='target_abv_percentage',
            field=models.FloatField(default=40.0, help_text='Target ABV % of the finished gin (10–99%)', validators=[django.core.validators.MinValueValidator(10.0), django.core.validators.MaxValueValidator(99.0)]),
        ),
    ]
