# Generated by Django 5.2.3 on 2026-06-24 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0002_ginrecipe_target_abv_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='ginrecipe',
            name='image_url',
            field=models.URLField(blank=True, default='', help_text='External image URL for this recipe'),
        ),
    ]
