# Generated by Django 5.2.3 on 2026-06-25 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0006_recipeingredient_ingredient_required'),
    ]

    operations = [
        migrations.AddField(
            model_name='ginrecipe',
            name='water_for_maceration',
            field=models.FloatField(default=0.0, help_text='Water needed for maceration in liters'),
        ),
    ]
