# Generated by Django 5.2.3 on 2026-06-27 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0007_ginrecipe_water_for_maceration'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=50)),
                ('deployed_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-deployed_at'],
            },
        ),
    ]
