# Generated by Django 5.2.3 on 2026-06-26 13:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0008_rename_ginrecipe_recipe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='target_abv_percentage',
            field=models.FloatField(default=40.0, help_text='Target ABV % of the finished spirit (10–99%)', validators=[django.core.validators.MinValueValidator(10.0), django.core.validators.MaxValueValidator(99.0)]),
        ),
    ]
