# Generated by Django 5.2.3 on 2026-06-26 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0009_alter_recipe_target_abv_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='category',
            field=models.CharField(choices=[('gin', 'Gin'), ('aquavit', 'Aquavit'), ('absinthe', 'Absinthe'), ('other', 'Other')], default='gin', max_length=20),
        ),
    ]
